### ISSUE TITLE
Looking forward the code to run demo

### ISSUE THREAD

**Issue by unihornWwan** [SysCV/vmt#3]
Hello, thank you for your open source work. 
May I ask if the team will provide demo code for reasoning of test video later? I remember that Mask Transfiner has demo code, is VMT coming soon? Thank you!

**Comment by lkeab** [comment]
Hi,  the code and instructions for running demo is [here](https://github.com/SysCV/vmt/blob/main/USAGE.md#results-visualization).

**Comment by unihornWwan** [comment]
> Hi, the code and instructions for running demo is [here](https://github.com/SysCV/vmt/blob/main/USAGE.md#results-visualization).

Thanks for your reply, I have modified it, and now I can run my own test video, but I have another question that I hope to get your answer: only a single GPU can be used in inference, so the video duration should not be very large (less than 60 frames). I guess the reason is that segmentation model needs to model the whole video to make use of space-time information, so the inference process cannot be changed to distributed. Is there any way to make inferences about longer videos? Looking forward to your reply, best wishes

**Comment by unihornWwan** [comment]
> Hi, the code and instructions for running demo is [here](https://github.com/SysCV/vmt/blob/main/USAGE.md#results-visualization).

Thanks for your reply, I have modified it, and now I can run my own test video, but I have another question that I hope to get your answer: only a single GPU can be used in inference, so the video duration should not be very large (less than 60 frames). I guess the reason is that segmentation model needs to model the whole video to make use of spatiotemporal information, so the inference process cannot be changed to distributed. Is there any way to inference longer videos? Looking forward to your reply, best wishes.

**Comment by lkeab** [comment]
Hi, when testing video length is larger than the clip length, you can set we set the video clip length to 40, and split the input video into multiple clips for inference. When splitting a long video, we keep a 10-frame overlap between neighboring clips. This implicitly helps maintain instance order.
